'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class control_panel_iframe
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''buttonStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonStatus As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxStatus As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''textBoxViewMessages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textBoxViewMessages As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''buttonAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonAlarm As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxAlarm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxAlarm As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonFire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonFire As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxFire control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxFire As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonLightBedR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonLightBedR1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxLightBedR1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxLightBedR1 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonLightBedR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonLightBedR2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxLightBedR2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxLightBedR2 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonLightBedR3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonLightBedR3 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxLightBedR3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxLightBedR3 As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonLiving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonLiving As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxLiving control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxLiving As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonDining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonDining As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxDining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxDining As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''buttonGarage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents buttonGarage As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''checkBoxGarage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkBoxGarage As Global.System.Web.UI.WebControls.CheckBox
End Class
